name: 'Upload Main Application'

on:
  workflow_dispatch:
  push:
    branches:
      - main

# Make sure we can only run one at a time
concurrency:
  group: '${{ github.workflow }}'
  cancel-in-progress: true

# The `jobs` key groups together all the jobs that run in the workflow file.
jobs:
  # This line defines a job with the ID `check-links` that is stored within the `jobs` key.
  upload:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Install
      - name: setup-dotnet
        uses: xt0rted/setup-dotnet@v1.5.0
        with:
          dotnet-version: 6.x
      - name: install tools
        run: dotnet tool install --global Microsoft.PowerApps.CLI.Tool


      # Package and archive
      - name: Package Solution
        run: pac solution pack -f ./src -pca -z package.zip
      - name: Upload Package to GH Actions
        uses: actions/upload-artifact@v3
        with:
          name: Solution
          path: package.zip

      # Upload to PowerPlatform
      # - name: Configure auths
      #   run: |
      #     pac auth create --name CalStateLA --applicationId $application_id --clientSecret $client_secret --tenant $tenant_id --environment  $environment_id
      #     pac auth select --name CalStateLA
      #   env:
      #     application_id: ${{ secrets.PAC_APPLICATION_ID }}
      #     client_secret: ${{ secrets.PAC_CLIENT_SECRET }}
      #     tenant_id: ${{ secrets.PAC_TENANT }}
      #     environment_id: ${{ secrets.PAC_ENVIRONMENT }}
      # - name: Upload Solution
      #   run: pac solution import -p package.zip
